# Generated by Django 2.1 on 2019-01-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_invaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='x_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='y_position',
            field=models.IntegerField(null=True),
        ),
    ]
